name: "envx_api"
services:
  postgres:
    image: postgres:17
    container_name: postgres_envx_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - envx_postgres_data:/var/lib/postgresql/data
volumes:
  envx_postgres_data:
